=== tduchateau/thymeleaf-eclipse-plugin/Dialects/Thymeleaf-Dialect.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
   Copyright 2013, Emanuel Rabina (http://www.ultraq.net.nz/)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<xsd:schema targetNamespace="http://www.ultraq.net.nz/eclipse/thymeleaf-dialect"
	xmlns="http://www.ultraq.net.nz/eclipse/thymeleaf-dialect"
	xmlns:ci="http://jaxb.dev.java.net/plugin/code-injector"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:extensionBindingPrefixes="ci" jxb:version="1.0"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<!-- Map schema to custom package -->
	<xsd:annotation>
		<xsd:appinfo>
			<jxb:schemaBindings>
				<jxb:package name="nz.net.ultraq.eclipse.thymeleaf.xml"/>
			</jxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>

	<!-- Root element, the dialect -->
	<xsd:element name="dialect">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:appinfo>
							<jxb:property name="processors"/>
						</xsd:appinfo>
					</xsd:annotation>
					<xsd:element name="attribute-processor" type="AttributeProcessor"/>
					<xsd:element name="element-processor" type="ElementProcessor"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="prefix" type="xsd:string" use="required"/>
			<xsd:attribute name="namespace-uri" type="xsd:anyURI" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<!-- Processor types -->
	<xsd:complexType name="Processor" abstract="true">
		<xsd:annotation>
			<xsd:appinfo>
				<ci:code>
	@javax.xml.bind.annotation.XmlTransient
	protected Dialect dialect;

	/**
	 * Gets the dialect this processor belongs to.
	 * 
	 * @return Dialect this processor is for.
	 */
	public Dialect getDialect() {

		return dialect;
	}

	/**
	 * Set the dialect this processor belongs to.
	 * 
	 * @param dialect
	 */
	public void setDialect(Dialect dialect) {

		this.dialect = dialect;
	}
				</ci:code>
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="AttributeProcessor">
		<xsd:complexContent>
			<xsd:extension base="Processor"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ElementProcessor">
		<xsd:complexContent>
			<xsd:extension base="Processor"/>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== tduchateau/thymeleaf-eclipse-plugin/Java/nz/net/ultraq/eclipse/thymeleaf/Standard-Dialect.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
   Copyright 2013, Emanuel Rabina (http://www.ultraq.net.nz/)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<dialect xmlns="http://www.ultraq.net.nz/eclipse/thymeleaf-dialect"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ultraq.net.nz/eclipse/thymeleaf-dialect Thymeleaf-Dialect.xsd"
	prefix="th">

	<!-- Introduced Thymeleaf attribute processors -->
	<attribute-processor name="alt-title"/>
	<attribute-processor name="attr"/>
	<attribute-processor name="attrappend"/>
	<attribute-processor name="attrprepend"/>
	<attribute-processor name="case"/>
	<attribute-processor name="each"/>
	<attribute-processor name="fragment"/>
	<attribute-processor name="object"/>
	<attribute-processor name="if"/>
	<attribute-processor name="inline"/>
	<attribute-processor name="unless"/>
	<attribute-processor name="include"/>
	<attribute-processor name="lang-xmllang"/>
	<attribute-processor name="remove"/>
	<attribute-processor name="substituteby"/>
	<attribute-processor name="swtich"/>
	<attribute-processor name="text"/>
	<attribute-processor name="utext"/>
	<attribute-processor name="with"/>
	<attribute-processor name="xmlbase"/>
	<attribute-processor name="xmllang"/>
	<attribute-processor name="xmlspace"/>
	<!-- Text inling processor??? -->

	<!-- Fixed value processors -->
	<attribute-processor name="async"/>
	<attribute-processor name="autofocus"/>
	<attribute-processor name="autoplay"/>
	<attribute-processor name="checked"/>
	<attribute-processor name="controls"/>
	<attribute-processor name="declare"/>
	<attribute-processor name="default"/>
	<attribute-processor name="defer"/>
	<attribute-processor name="disabled"/>
	<attribute-processor name="formnovalidate"/>
	<attribute-processor name="hidden"/>
	<attribute-processor name="ismap"/>
	<attribute-processor name="loop"/>
	<attribute-processor name="multiple"/>
	<attribute-processor name="novalidate"/>
	<attribute-processor name="nowrap"/>
	<attribute-processor name="open"/>
	<attribute-processor name="pubdate"/>
	<attribute-processor name="readonly"/>
	<attribute-processor name="required"/>
	<attribute-processor name="reversed"/>
	<attribute-processor name="selected"/>
	<attribute-processor name="scoped"/>
	<attribute-processor name="seamless"/>

	<!-- Event processors -->
	<attribute-processor name="onabort"/>
	<attribute-processor name="onafterprint"/>
	<attribute-processor name="onbeforeprint"/>
	<attribute-processor name="onbeforeunload"/>
	<attribute-processor name="onblur"/>
	<attribute-processor name="oncanplay"/>
	<attribute-processor name="oncanplaythrough"/>
	<attribute-processor name="onchange"/>
	<attribute-processor name="onclick"/>
	<attribute-processor name="oncontextmenu"/>
	<attribute-processor name="ondblclick"/>
	<attribute-processor name="ondrag"/>
	<attribute-processor name="ondragend"/>
	<attribute-processor name="ondragenter"/>
	<attribute-processor name="ondragleave"/>
	<attribute-processor name="ondragover"/>
	<attribute-processor name="ondragstart"/>
	<attribute-processor name="ondrop"/>
	<attribute-processor name="ondurationchanged"/>
	<attribute-processor name="onemptied"/>
	<attribute-processor name="onended"/>
	<attribute-processor name="onerror"/>
	<attribute-processor name="onfocus"/>
	<attribute-processor name="onformchange"/>
	<attribute-processor name="onforminput"/>
	<attribute-processor name="onhashchange"/>
	<attribute-processor name="oninput"/>
	<attribute-processor name="oninvalid"/>
	<attribute-processor name="onkeydown"/>
	<attribute-processor name="onkeypress"/>
	<attribute-processor name="onkeyup"/>
	<attribute-processor name="onload"/>
	<attribute-processor name="onloadeddata"/>
	<attribute-processor name="onloadedmetadata"/>
	<attribute-processor name="onloadstart"/>
	<attribute-processor name="onmessage"/>
	<attribute-processor name="onmousedown"/>
	<attribute-processor name="onmousemove"/>
	<attribute-processor name="onmouseout"/>
	<attribute-processor name="onmouseover"/>
	<attribute-processor name="onmouseup"/>
	<attribute-processor name="onmousewheel"/>
	<attribute-processor name="onoffline"/>
	<attribute-processor name="ononline"/>
	<attribute-processor name="onpause"/>
	<attribute-processor name="onplay"/>
	<attribute-processor name="onplaying"/>
	<attribute-processor name="onpopstate"/>
	<attribute-processor name="onprogress"/>
	<attribute-processor name="onratechange"/>
	<attribute-processor name="onreadystatechange"/>
	<attribute-processor name="onredo"/>
	<attribute-processor name="onreset"/>
	<attribute-processor name="onresize"/>
	<attribute-processor name="onscroll"/>
	<attribute-processor name="onseeked"/>
	<attribute-processor name="onseeking"/>
	<attribute-processor name="onselect"/>
	<attribute-processor name="onshow"/>
	<attribute-processor name="onstalled"/>
	<attribute-processor name="onstorage"/>
	<attribute-processor name="onsubmit"/>
	<attribute-processor name="onsuspend"/>
	<attribute-processor name="ontimeupdate"/>
	<attribute-processor name="onundo"/>
	<attribute-processor name="onunload"/>
	<attribute-processor name="onvolumechange"/>
	<attribute-processor name="onwaiting"/>

	<!-- Non-removable attribute processors -->
	<attribute-processor name="action"/>
	<attribute-processor name="href"/>
	<attribute-processor name="name"/>
	<attribute-processor name="src"/>
	<attribute-processor name="type"/>
	<attribute-processor name="value"/>

	<!-- Removable attribute processors -->
	<attribute-processor name="abbr"/>
	<attribute-processor name="accept"/>
	<attribute-processor name="accept-charset"/>
	<attribute-processor name="accesskey"/>
	<attribute-processor name="align"/>
	<attribute-processor name="alt"/>
	<attribute-processor name="archive"/>
	<attribute-processor name="audio"/>
	<attribute-processor name="autocomplete"/>
	<attribute-processor name="axis"/>
	<attribute-processor name="background"/>
	<attribute-processor name="bgcolor"/>
	<attribute-processor name="border"/>
	<attribute-processor name="cellpadding"/>
	<attribute-processor name="cellspacing"/>
	<attribute-processor name="challenge"/>
	<attribute-processor name="charset"/>
	<attribute-processor name="cite"/>
	<attribute-processor name="class"/>
	<attribute-processor name="classid"/>
	<attribute-processor name="codebase"/>
	<attribute-processor name="codetype"/>
	<attribute-processor name="cols"/>
	<attribute-processor name="colspan"/>
	<attribute-processor name="compact"/>
	<attribute-processor name="content"/>
	<attribute-processor name="contenteditable"/>
	<attribute-processor name="contextmenu"/>
	<attribute-processor name="data"/>
	<attribute-processor name="datetime"/>
	<attribute-processor name="dir"/>
	<attribute-processor name="draggable"/>
	<attribute-processor name="dropzone"/>
	<attribute-processor name="enctype"/>
	<attribute-processor name="for"/>
	<attribute-processor name="form"/>
	<attribute-processor name="formaction"/>
	<attribute-processor name="formenctype"/>
	<attribute-processor name="formmethod"/>
	<attribute-processor name="formtarget"/>
	<attribute-processor name="frame"/>
	<attribute-processor name="frameborder"/>
	<attribute-processor name="headers"/>
	<attribute-processor name="height"/>
	<attribute-processor name="high"/>
	<attribute-processor name="hreflang"/>
	<attribute-processor name="hspace"/>
	<attribute-processor name="http-equiv"/>
	<attribute-processor name="icon"/>
	<attribute-processor name="id"/>
	<attribute-processor name="keytype"/>
	<attribute-processor name="kind"/>
	<attribute-processor name="label"/>
	<attribute-processor name="lang"/>
	<attribute-processor name="list"/>
	<attribute-processor name="longdesc"/>
	<attribute-processor name="low"/>
	<attribute-processor name="manifest"/>
	<attribute-processor name="marginheight"/>
	<attribute-processor name="marginwidth"/>
	<attribute-processor name="max"/>
	<attribute-processor name="maxlength"/>
	<attribute-processor name="media"/>
	<attribute-processor name="method"/>
	<attribute-processor name="min"/>
	<attribute-processor name="optimum"/>
	<attribute-processor name="pattern"/>
	<attribute-processor name="placeholder"/>
	<attribute-processor name="poster"/>
	<attribute-processor name="preload"/>
	<attribute-processor name="radiogroup"/>
	<attribute-processor name="rel"/>
	<attribute-processor name="rev"/>
	<attribute-processor name="rows"/>
	<attribute-processor name="rowspan"/>
	<attribute-processor name="rules"/>
	<attribute-processor name="sandbox"/>
	<attribute-processor name="scheme"/>
	<attribute-processor name="scope"/>
	<attribute-processor name="scrolling"/>
	<attribute-processor name="size"/>
	<attribute-processor name="sizes"/>
	<attribute-processor name="span"/>
	<attribute-processor name="spellcheck"/>
	<attribute-processor name="standby"/>
	<attribute-processor name="style"/>
	<attribute-processor name="srclang"/>
	<attribute-processor name="start"/>
	<attribute-processor name="step"/>
	<attribute-processor name="summary"/>
	<attribute-processor name="tabindex"/>
	<attribute-processor name="target"/>
	<attribute-processor name="title"/>
	<attribute-processor name="usemap"/>
	<attribute-processor name="valuetype"/>
	<attribute-processor name="vspace"/>
	<attribute-processor name="width"/>
